### PR TITLE
Add Jetbrains files to gitignore

### PR DESCRIPTION
**Pull request by DiSiqueira**

### CODE REVIEW

**Comment by rjeczalik** [comment]
Hey @DiSiqueira! While you're at it, could I ask you to bump go version to 1.7.5 + tip for travis and push to this PR?

**Comment by DiSiqueira** [comment]
Is this what are you expecting? Not sure if i did this in the right way.

**Comment by rjeczalik** [comment]
:+1:

**Comment by nathany** [comment]
@DiSiqueira TIP: you can create a global gitignore to exclude `.idea` from all projects on your system. https://help.github.com/articles/ignoring-files/#create-a-global-gitignore

**Comment by DiSiqueira** [comment]
Thank you for this @nathany!! This will make a lot of things easier, really appreciate your tip!! 😃

**Pull request merged**
