### PR TITLE
Fix fsevents under Go 1.6 CGO rules

### PR DESCRIPTION
**Pull request by adg**
Should fix issue #90 on darwin.

### CODE REVIEW

**Comment by nathany** [comment]
Thanks Andrew.

@rjeczalik The tests pass, but fail on something with gocover. Any ideas? 

Note the tests aren't running against Go 1.6 without also changing the Travis config. #92.

**Comment by rjeczalik** [comment]
Hey @adg! Thanks for the PR, can I ask you to rebase with master?

**Comment by adg** [comment]
@rjeczalik done!

**Comment by rjeczalik** [comment]
Yay, thanks!

**Pull request merged**
